```{r}
library(dplyr)
library(tidyr)
library(magrittr)
```


Our results for table 6 go here

```{r}
alpha.list <- c(0.01, 0.02, 0.05, 0.1, 0.2) 
n.list <- c(10, 20, 50, 100, 200, 500)
df <- readRDS("../data/processed/tab6.rds")
df %>% filter(n %in% n.list) %>% group_by(n, alpha) %>% summarise(cv = mean(cv), .groups = "drop_last") -> df_ours
#
Tab6 <- read.csv("../data/external/Table6.csv")
colnames(Tab6)= c("alpha", "10", "20", "50", "100", "200", "500")
Tab6_long <- tidyr::gather(Tab6, key = n, value = cv, "10":"500") %>% mutate(n = as.numeric(n)) %>% filter(n %in% n.list)
tabR <- merge(df_ours, Tab6_long, by=c("alpha", "n")) %>% mutate(R = cv.x/cv.y)
```

Here are the results of our calculations


```{r}
tabR %>% select(alpha, n, cv.x) %>% spread(n, cv.x) %>% round(3) -> tab
colnames(tab) <- as.vector(c("alpha", sapply(colnames(tab)[-1], function(n) paste("n=",n))))
knitr::kable(head(tab), col.names = gsub("[.]", " ", names(tab)))
```



For comparison, below the table from the paper is presented:

```{r}
tabR %>% select(alpha, n, cv.y) %>% spread(n, cv.y) %>% round(3) -> tab
colnames(tab) <- as.vector(c("alpha", sapply(colnames(tab)[-1], function(n) paste("n=",n))))
knitr::kable(head(tab), col.names = gsub("[.]", " ", names(tab)))
```


Here is the ratio of the results for comparison

```{r}
tabR %>% select(alpha, n, R) %>% spread(n, R) %>% round(3) -> tab
colnames(tab) <- as.vector(c("alpha", sapply(colnames(tab)[-1], function(n) paste("n=",n))))
knitr::kable(head(tab), col.names = gsub("[.]", " ", names(tab)))
```


